# Generated by Django 3.2 on 2021-05-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210506_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_active',
        ),
    ]
