# Generated by Django 3.2 on 2021-05-06 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_table_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='min_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
