# Generated by Django 3.2 on 2021-05-08 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_table_min_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='min_guests',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
