# Generated by Django 3.2 on 2021-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_table_min_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'permissions': (('manage_place', 'Manage place'),)},
        ),
    ]
